Voy a preparar dos archivos .tsv para la obtención de gráficas en FragPipe-Analyst. 

- Archivo de abundancias tumoral/normal ordenadas
- Archivo de anotación con los datos de cada muestra ordenados

Quiero eliminar de esos dos archivos las muestras que han sido descalificadas por patología previa y las muestras normales ductales, para quedarme con las 135 muestras tumorales y 67 NAT.

In [2]:
import os
import pickle as pkl
import pandas as pd

In [15]:
muestras_descalificadas = ["CPT0063990003", "C3L-01687-04", "CPT0166680004", "CPT0088840004", "CPT0247050003", "CPT0237290004", "CPT0275870003", "CPT0275880003", "CPT0094760003", "CPT0162600005", "C3N-01900-04", "CPT0198730004", "CPT0162830005", "CPT0014060003", "CPT0224470004", "CPT0186050004", "CPT0108410003", "CPT0355180003", "CPT0355200003", "CPT0264180003", "CPT0126200003", "CPT0109130003", "CPT0248320003", "CPT0166930004", "CPT0198340004", "CPT0355180003", "CPT0355200003", "CPT0355190003", "CPT0347760002", "CPT0347790002", "CPT0347820002", "CPT0347850002", "CPT0347880002"]

In [16]:
abundance = pd.read_csv('abundance_gene_MD_order.tsv', sep='\t')
abundance

,Index,NumberPSM,ProteinID,MaxPepProb,ReferenceIntensity,CPT0237840004,CPT0166760004,CPT0094630004,CPT0063970004,CPT0081260004,...,CPT0078180003,CPT0197440004,CPT0355180003,CPT0355200003,CPT0355190003,CPT0347760002,CPT0347790002,CPT0347820002,CPT0347850002,CPT0347880002
0,A1BG,1395,P04217,1.0,28.716163,28.499551,28.452195,28.630157,29.174342,29.585927,...,28.496110,30.102289,29.425028,29.418836,28.214312,28.488643,28.385020,27.729956,28.458926,27.808411
1,A1CF,247,Q9NQ94,1.0,24.592863,24.018242,23.500280,24.174142,23.972000,24.501145,...,26.447539,23.165488,24.149451,25.233385,25.799610,25.981225,25.599940,25.914578,25.671271,26.218836
2,A2M,7832,P01023,1.0,29.941210,29.373080,29.038021,29.764657,30.442977,29.902549,...,29.658957,31.312727,30.928961,30.305615,29.207896,30.546957,29.339427,28.685161,29.364176,29.249406
3,A2ML1,141,A8K2U0,1.0,21.881356,NaN,NaN,NaN,NaN,NaN,...,22.009275,21.229600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,A4GALT,3,Q9NPC4,1.0,16.076463,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12115,ZXDC,3,Q2QGD7,1.0,15.456372,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12116,ZYG11B,67,Q9C0D3,1.0,20.805448,20.918340,20.842082,20.881666,20.944515,21.111598,...,21.109123,20.985639,20.867963,20.997213,20.730738,20.547531,20.861241,20.549092,20.461376,20.356947
12117,ZYX,1854,Q15942,1.0,28.865534,28.917052,28.813093,28.692954,29.264926,29.331659,...,28.397063,28.819882,29.257749,28.014804,27.562795,27.765326,28.010625,27.360692,27.641424,27.304978
12118,ZZEF1,760,O43149,1.0,24.928770,25.079604,24.908095,24.953850,24.950274,24.707046,...,24.800248,24.973129,24.794404,24.702706,25.008415,24.978352,24.781041,25.387207,25.235190,25.447507
12119,ZZZ3,29,Q8IYH5,1.0,19.858194,NaN,NaN,NaN,NaN,NaN,...,20.349678,19.592919,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
# Eliminar las muestras descalificadas del dataframe
abundance = abundance.drop(columns=["CPT0063990003", "C3L-01687-04", "CPT0166680004", "CPT0088840004", "CPT0247050003"])
abundance

,Index,NumberPSM,ProteinID,MaxPepProb,ReferenceIntensity,CPT0237840004,CPT0166760004,CPT0094630004,CPT0063970004,CPT0081260004,...,CPT0078180003,CPT0197440004,CPT0355180003,CPT0355200003,CPT0355190003,CPT0347760002,CPT0347790002,CPT0347820002,CPT0347850002,CPT0347880002
0,A1BG,1395,P04217,1.0,28.716163,28.499551,28.452195,28.630157,29.174342,29.585927,...,28.496110,30.102289,29.425028,29.418836,28.214312,28.488643,28.385020,27.729956,28.458926,27.808411
1,A1CF,247,Q9NQ94,1.0,24.592863,24.018242,23.500280,24.174142,23.972000,24.501145,...,26.447539,23.165488,24.149451,25.233385,25.799610,25.981225,25.599940,25.914578,25.671271,26.218836
2,A2M,7832,P01023,1.0,29.941210,29.373080,29.038021,29.764657,30.442977,29.902549,...,29.658957,31.312727,30.928961,30.305615,29.207896,30.546957,29.339427,28.685161,29.364176,29.249406
3,A2ML1,141,A8K2U0,1.0,21.881356,NaN,NaN,NaN,NaN,NaN,...,22.009275,21.229600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,A4GALT,3,Q9NPC4,1.0,16.076463,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12115,ZXDC,3,Q2QGD7,1.0,15.456372,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12116,ZYG11B,67,Q9C0D3,1.0,20.805448,20.918340,20.842082,20.881666,20.944515,21.111598,...,21.109123,20.985639,20.867963,20.997213,20.730738,20.547531,20.861241,20.549092,20.461376,20.356947
12117,ZYX,1854,Q15942,1.0,28.865534,28.917052,28.813093,28.692954,29.264926,29.331659,...,28.397063,28.819882,29.257749,28.014804,27.562795,27.765326,28.010625,27.360692,27.641424,27.304978
12118,ZZEF1,760,O43149,1.0,24.928770,25.079604,24.908095,24.953850,24.950274,24.707046,...,24.800248,24.973129,24.794404,24.702706,25.008415,24.978352,24.781041,25.387207,25.235190,25.447507
12119,ZZZ3,29,Q8IYH5,1.0,19.858194,NaN,NaN,NaN,NaN,NaN,...,20.349678,19.592919,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
abundance = abundance.drop(columns=["CPT0237290004", "CPT0275870003", "CPT0275880003", "CPT0094760003", "CPT0162600005", "C3N-01900-04", "CPT0198730004"])
abundance

,Index,NumberPSM,ProteinID,MaxPepProb,ReferenceIntensity,CPT0237840004,CPT0166760004,CPT0094630004,CPT0063970004,CPT0081260004,...,CPT0078180003,CPT0197440004,CPT0355180003,CPT0355200003,CPT0355190003,CPT0347760002,CPT0347790002,CPT0347820002,CPT0347850002,CPT0347880002
0,A1BG,1395,P04217,1.0,28.716163,28.499551,28.452195,28.630157,29.174342,29.585927,...,28.496110,30.102289,29.425028,29.418836,28.214312,28.488643,28.385020,27.729956,28.458926,27.808411
1,A1CF,247,Q9NQ94,1.0,24.592863,24.018242,23.500280,24.174142,23.972000,24.501145,...,26.447539,23.165488,24.149451,25.233385,25.799610,25.981225,25.599940,25.914578,25.671271,26.218836
2,A2M,7832,P01023,1.0,29.941210,29.373080,29.038021,29.764657,30.442977,29.902549,...,29.658957,31.312727,30.928961,30.305615,29.207896,30.546957,29.339427,28.685161,29.364176,29.249406
3,A2ML1,141,A8K2U0,1.0,21.881356,NaN,NaN,NaN,NaN,NaN,...,22.009275,21.229600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,A4GALT,3,Q9NPC4,1.0,16.076463,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12115,ZXDC,3,Q2QGD7,1.0,15.456372,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12116,ZYG11B,67,Q9C0D3,1.0,20.805448,20.918340,20.842082,20.881666,20.944515,21.111598,...,21.109123,20.985639,20.867963,20.997213,20.730738,20.547531,20.861241,20.549092,20.461376,20.356947
12117,ZYX,1854,Q15942,1.0,28.865534,28.917052,28.813093,28.692954,29.264926,29.331659,...,28.397063,28.819882,29.257749,28.014804,27.562795,27.765326,28.010625,27.360692,27.641424,27.304978
12118,ZZEF1,760,O43149,1.0,24.928770,25.079604,24.908095,24.953850,24.950274,24.707046,...,24.800248,24.973129,24.794404,24.702706,25.008415,24.978352,24.781041,25.387207,25.235190,25.447507
12119,ZZZ3,29,Q8IYH5,1.0,19.858194,NaN,NaN,NaN,NaN,NaN,...,20.349678,19.592919,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
abundance = abundance.drop(columns=["CPT0162830005", "CPT0014060003", "CPT0224470004", "CPT0186050004", "CPT0108410003", "CPT0355180003", "CPT0355200003"])
abundance

,Index,NumberPSM,ProteinID,MaxPepProb,ReferenceIntensity,CPT0237840004,CPT0166760004,CPT0094630004,CPT0063970004,CPT0081260004,...,CPT0066020003,CPT0236360004,CPT0078180003,CPT0197440004,CPT0355190003,CPT0347760002,CPT0347790002,CPT0347820002,CPT0347850002,CPT0347880002
0,A1BG,1395,P04217,1.0,28.716163,28.499551,28.452195,28.630157,29.174342,29.585927,...,28.731824,28.551851,28.496110,30.102289,28.214312,28.488643,28.385020,27.729956,28.458926,27.808411
1,A1CF,247,Q9NQ94,1.0,24.592863,24.018242,23.500280,24.174142,23.972000,24.501145,...,24.391285,26.156286,26.447539,23.165488,25.799610,25.981225,25.599940,25.914578,25.671271,26.218836
2,A2M,7832,P01023,1.0,29.941210,29.373080,29.038021,29.764657,30.442977,29.902549,...,30.017886,29.952439,29.658957,31.312727,29.207896,30.546957,29.339427,28.685161,29.364176,29.249406
3,A2ML1,141,A8K2U0,1.0,21.881356,NaN,NaN,NaN,NaN,NaN,...,21.444055,22.004818,22.009275,21.229600,NaN,NaN,NaN,NaN,NaN,NaN
4,A4GALT,3,Q9NPC4,1.0,16.076463,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12115,ZXDC,3,Q2QGD7,1.0,15.456372,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12116,ZYG11B,67,Q9C0D3,1.0,20.805448,20.918340,20.842082,20.881666,20.944515,21.111598,...,20.618088,20.693109,21.109123,20.985639,20.730738,20.547531,20.861241,20.549092,20.461376,20.356947
12117,ZYX,1854,Q15942,1.0,28.865534,28.917052,28.813093,28.692954,29.264926,29.331659,...,28.946584,28.340699,28.397063,28.819882,27.562795,27.765326,28.010625,27.360692,27.641424,27.304978
12118,ZZEF1,760,O43149,1.0,24.928770,25.079604,24.908095,24.953850,24.950274,24.707046,...,24.750446,24.773645,24.800248,24.973129,25.008415,24.978352,24.781041,25.387207,25.235190,25.447507
12119,ZZZ3,29,Q8IYH5,1.0,19.858194,NaN,NaN,NaN,NaN,NaN,...,20.582178,21.024766,20.349678,19.592919,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
abundance = abundance.drop(columns=["CPT0264180003", "CPT0126200003", "CPT0109130003", "CPT0248320003", "CPT0166930004", "CPT0198340004"])
abundance

,Index,NumberPSM,ProteinID,MaxPepProb,ReferenceIntensity,CPT0237840004,CPT0166760004,CPT0094630004,CPT0063970004,CPT0081260004,...,CPT0066020003,CPT0236360004,CPT0078180003,CPT0197440004,CPT0355190003,CPT0347760002,CPT0347790002,CPT0347820002,CPT0347850002,CPT0347880002
0,A1BG,1395,P04217,1.0,28.716163,28.499551,28.452195,28.630157,29.174342,29.585927,...,28.731824,28.551851,28.496110,30.102289,28.214312,28.488643,28.385020,27.729956,28.458926,27.808411
1,A1CF,247,Q9NQ94,1.0,24.592863,24.018242,23.500280,24.174142,23.972000,24.501145,...,24.391285,26.156286,26.447539,23.165488,25.799610,25.981225,25.599940,25.914578,25.671271,26.218836
2,A2M,7832,P01023,1.0,29.941210,29.373080,29.038021,29.764657,30.442977,29.902549,...,30.017886,29.952439,29.658957,31.312727,29.207896,30.546957,29.339427,28.685161,29.364176,29.249406
3,A2ML1,141,A8K2U0,1.0,21.881356,NaN,NaN,NaN,NaN,NaN,...,21.444055,22.004818,22.009275,21.229600,NaN,NaN,NaN,NaN,NaN,NaN
4,A4GALT,3,Q9NPC4,1.0,16.076463,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12115,ZXDC,3,Q2QGD7,1.0,15.456372,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12116,ZYG11B,67,Q9C0D3,1.0,20.805448,20.918340,20.842082,20.881666,20.944515,21.111598,...,20.618088,20.693109,21.109123,20.985639,20.730738,20.547531,20.861241,20.549092,20.461376,20.356947
12117,ZYX,1854,Q15942,1.0,28.865534,28.917052,28.813093,28.692954,29.264926,29.331659,...,28.946584,28.340699,28.397063,28.819882,27.562795,27.765326,28.010625,27.360692,27.641424,27.304978
12118,ZZEF1,760,O43149,1.0,24.928770,25.079604,24.908095,24.953850,24.950274,24.707046,...,24.750446,24.773645,24.800248,24.973129,25.008415,24.978352,24.781041,25.387207,25.235190,25.447507
12119,ZZZ3,29,Q8IYH5,1.0,19.858194,NaN,NaN,NaN,NaN,NaN,...,20.582178,21.024766,20.349678,19.592919,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
abundance = abundance.drop(columns=["CPT0355190003", "CPT0347760002", "CPT0347790002", "CPT0347820002", "CPT0347850002", "CPT0347880002"])
abundance

,Index,NumberPSM,ProteinID,MaxPepProb,ReferenceIntensity,CPT0237840004,CPT0166760004,CPT0094630004,CPT0063970004,CPT0081260004,...,CPT0187540004,C3N-00709-06,CPT0127290003,CPT0123890003,C3L-00401-04,CPT0236710004,CPT0066020003,CPT0236360004,CPT0078180003,CPT0197440004
0,A1BG,1395,P04217,1.0,28.716163,28.499551,28.452195,28.630157,29.174342,29.585927,...,27.919308,28.368991,28.250506,28.407259,29.868854,28.273358,28.731824,28.551851,28.496110,30.102289
1,A1CF,247,Q9NQ94,1.0,24.592863,24.018242,23.500280,24.174142,23.972000,24.501145,...,25.958520,26.109642,26.158056,25.959796,24.443747,25.750190,24.391285,26.156286,26.447539,23.165488
2,A2M,7832,P01023,1.0,29.941210,29.373080,29.038021,29.764657,30.442977,29.902549,...,29.739066,30.356308,29.508487,29.382712,30.782345,28.718255,30.017886,29.952439,29.658957,31.312727
3,A2ML1,141,A8K2U0,1.0,21.881356,NaN,NaN,NaN,NaN,NaN,...,20.798894,21.201422,NaN,NaN,20.503960,20.381522,21.444055,22.004818,22.009275,21.229600
4,A4GALT,3,Q9NPC4,1.0,16.076463,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12115,ZXDC,3,Q2QGD7,1.0,15.456372,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,15.964854,13.722731,NaN,NaN,NaN,NaN
12116,ZYG11B,67,Q9C0D3,1.0,20.805448,20.918340,20.842082,20.881666,20.944515,21.111598,...,20.956435,21.102749,20.855694,20.961436,20.957091,21.166533,20.618088,20.693109,21.109123,20.985639
12117,ZYX,1854,Q15942,1.0,28.865534,28.917052,28.813093,28.692954,29.264926,29.331659,...,28.291135,28.081646,28.075227,28.576476,29.080518,28.312253,28.946584,28.340699,28.397063,28.819882
12118,ZZEF1,760,O43149,1.0,24.928770,25.079604,24.908095,24.953850,24.950274,24.707046,...,25.194444,25.055802,25.001542,24.640902,24.445590,25.334794,24.750446,24.773645,24.800248,24.973129
12119,ZZZ3,29,Q8IYH5,1.0,19.858194,NaN,NaN,NaN,NaN,NaN,...,20.258056,19.914253,20.019647,19.911075,19.762162,20.518658,20.582178,21.024766,20.349678,19.592919

In [25]:
# Guardar el dataframe en formato tsv
abundance.to_csv('abundance_gene_202_samples.tsv', sep='\t', index=False)

In [26]:
annotation = pd.read_csv('experiment_annotation.tsv', sep='\t')
annotation

,plex,channel,Sample,sample_name,condition,replicate,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,TMT_01s,127C,CPT0237840004,C3N-03884,Tumor,1,NaN,NaN,NaN,NaN
1,TMT_01s,129C,CPT0166760004,C3L-03123,Tumor,1,NaN,NaN,NaN,NaN
2,TMT_01s,130N,CPT0094630004,C3L-01687,Tumor,1,NaN,NaN,NaN,NaN
3,TMT_01s,130C,CPT0063970004,C3L-00589,Tumor,1,NaN,NaN,NaN,NaN
4,TMT_01s,131C,CPT0081260004,C3L-00599,Tumor,1,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
229,TMT_25s,129C,CPT0347760002,C3L-07032,NAT,1,NaN,NaN,NaN,NaN
230,TMT_25s,130N,CPT0347790002,C3L-07033,NAT,1,NaN,NaN,NaN,NaN
231,TMT_25s,130C,CPT0347820002,C3L-07034,NAT,1,NaN,NaN,NaN,NaN
232,TMT_25s,131N,CPT0347850002,C3L-07035,NAT,1,NaN,NaN,NaN,NaN
233,TMT_25s,131C,CPT0347880002,C3L-07036,NAT,1,NaN,NaN,NaN,NaN

In [27]:
annotation = annotation.drop(columns=["Unnamed: 6", "Unnamed: 7", "Unnamed: 8", "Unnamed: 9"])
annotation

        plex channel         Sample sample_name condition  replicate
0    TMT_01s    127C  CPT0237840004   C3N-03884     Tumor          1
1    TMT_01s    129C  CPT0166760004   C3L-03123     Tumor          1
2    TMT_01s    130N  CPT0094630004   C3L-01687     Tumor          1
3    TMT_01s    130C  CPT0063970004   C3L-00589     Tumor          1
4    TMT_01s    131C  CPT0081260004   C3L-00599     Tumor          1
..       ...     ...            ...         ...       ...        ...
229  TMT_25s    129C  CPT0347760002   C3L-07032       NAT          1
230  TMT_25s    130N  CPT0347790002   C3L-07033       NAT          1
231  TMT_25s    130C  CPT0347820002   C3L-07034       NAT          1
232  TMT_25s    131N  CPT0347850002   C3L-07035       NAT          1
233  TMT_25s    131C  CPT0347880002   C3L-07036       NAT          1

[234 rows x 6 columns]

In [28]:
annotation = annotation.loc[~annotation['Sample'].isin(muestras_descalificadas)]
annotation

        plex channel         Sample sample_name condition  replicate
0    TMT_01s    127C  CPT0237840004   C3N-03884     Tumor          1
1    TMT_01s    129C  CPT0166760004   C3L-03123     Tumor          1
2    TMT_01s    130N  CPT0094630004   C3L-01687     Tumor          1
3    TMT_01s    130C  CPT0063970004   C3L-00589     Tumor          1
4    TMT_01s    131C  CPT0081260004   C3L-00599     Tumor          1
..       ...     ...            ...         ...       ...        ...
220  TMT_23s    130N  CPT0236710004   C3N-03839       NAT          1
222  TMT_23s    131N  CPT0066020003   C3N-01011       NAT          1
223  TMT_24s    128N  CPT0236360004   C3N-03069       NAT          1
224  TMT_24s    130C  CPT0078180003   C3N-00512       NAT          1
225  TMT_24s    131C  CPT0197440004   C3L-02899       NAT          1

[203 rows x 6 columns]

In [29]:
# Guardar el dataframe en formato tsv
annotation.to_csv('experiment_annotation_202_samples.tsv', sep='\t', index=False)